// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RunOnStartVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "RunOnStartVS.014bae42-901e-4ffc-89c4-edb280bc8f28";
        public const string Name = "RunOnStartVS";
        public const string Description = @"Execute run-on-startup.ps1 files whenever a solution is opened.";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
